### PR TITLE
add enum values for number

### PR DESCRIPTION
**Pull request by wjh000123**

### CODE REVIEW

**Review by willfarrell — CHANGES_REQUESTED** [review]
perhaps `values.push(item)` can be moved to an `else` statement?

**Comment by wjh000123** [comment]
I'm not quite familiar with JSON schema, what if the enum value is object or other type?

**Comment by willfarrell** [comment]
`enum` can only be a string, number, boolean or null. For array and object the enum would be a deeper level.
https://spacetelescope.github.io/understanding-json-schema/reference/generic.html

**Comment by willfarrell** [comment]
Included in v0.1.7

**Pull request closed without merging**
